Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class LocationController : Controller
    {
        private readonly CountryDAL _countryDal = new CountryDAL();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult AddCountry(CountryModel model)
        {
            try
            {
                    _countryDal.AddCountry(model);
                   
                    return Json(true);
            }
            catch
            {
                return Json(false);
            }
        }







        public ActionResult Create()
        {
            var countries = new List<CountryModel>
        {
            new CountryModel { CountryId = 1, CountryName = "India" }
        };

            // States for India
            var states = new List<StateModel>
        {
            new StateModel { StateId = 1, StateName = "Delhi", CountryId = 1 },
            new StateModel { StateId = 2, StateName = "Uttar Pradesh", CountryId = 1 },
            new StateModel { StateId = 3, StateName = "Maharashtra", CountryId = 1 }
        };

            // Pass country and states to ViewBag
            ViewBag.Country = new SelectList(countries, "CountryId", "CountryName");
            ViewBag.State = new SelectList(states, "StateId", "StateName");

            return View();
        }

        [HttpPost]
        public ActionResult Create(EmployeeModel model)
        {
            // Here, model.fk_Country_Id and model.fk_State_Id will have the selected IDs
            // Save the data as per your requirement

            return RedirectToAction("Index");
        }
    }
}

Views/Location/Create.cshtml
@model WebApplication4.Models.EmployeeModel

<h2>Create Employee</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <!-- Country Dropdown -->
        <div class="form-group">
            @Html.LabelFor(model => model.FK_Country_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_Country_Id, (SelectList)ViewBag.Country, "Select Country", new { @class = "form-control", disabled = "disabled" })
            </div>
        </div>

        <!-- State Dropdown -->
        <div class="form-group">
            @Html.LabelFor(model => model.FK_State_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_State_Id, (SelectList)ViewBag.State, "Select State", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Views/Location/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
    <title> Index </title>
        <div>
            <label>Country Name:</label>
            <input type="text" id="countryName" />
        </div>
        <div>
            <label>Is Active:</label>
            <input type="checkbox" id="isActive" />
        </div>
        <div>
            <label>Is Delete:</label>
            <input type="checkbox" id="isDelete" />
        </div>
        <div>
            <button id="addCountryBtn">Add Country</button>
        </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
    //$(document).ready(function () {
    //    console.log("jQuery is loaded and ready!");
    //});
   $(document).ready(function () {
    $('#addCountryBtn').click(function () {
        var countryName = $('#countryName').val();
        var isActive = $('#isActive').is(':checked');
        var isDeleted = $('#isDeleted').is(':checked');

        $.ajax({
            url: '@Url.Action("AddCountry", "Location")',
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify({
                CountryName: countryName,
                IsActive: isActive,
                IsDeleted: isDeleted
            }),
            success: function (response) {
                if (response) {
                    alert("Country added successfully!");
                } else {
                    alert("Error: Could not add the country.");
                }
            },
            error: function () {
                alert("An unexpected error occurred.");
            }
        });
    });
});

</script>
