Controllers/ShiftController.cs
using companyProject;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class ShiftController : Controller
    {
        private readonly ShiftDAL sd = new ShiftDAL();
        private readonly CompanyDAL _companyDAL = new CompanyDAL();

        public ActionResult Index()
        {

            var s = sd.GetShift();
            return View(s);
        }

        public ActionResult Create()
        {
            
            var companies = _companyDAL.getAllCompany();
            ViewBag.Companies = new SelectList(companies, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ShiftModel shift, HttpPostedFileBase file)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        int shiftId = sd.AddShifts(shift);

                        string directoryPath = Server.MapPath("~/Images/SubImages");


                        if (!Directory.Exists(directoryPath))
                        {
                            Directory.CreateDirectory(directoryPath);
                        }

                        string fileName = $"{shiftId}_{Path.GetFileName(file.FileName)}";
                        string filePath = Path.Combine(directoryPath, fileName);


                        file.SaveAs(filePath);

                        shift.imagepath = $"~/Images/SubImages/{fileName}";
                        shift.Id = shiftId;
                        sd.UpdateShift(shift);


                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.ErrorMessage("Please upload an image.");
                    }
                }
            }
            catch (Exception ex)
            {

                ViewBag.ErrorMessage($"An error occurred: {ex.Message}");
            }
            var companies = _companyDAL.getAllCompany();
            ViewBag.Companies = new SelectList(companies, "Id", "Name");

            return View(shift);
        }




        public ActionResult Edit(int id)
        {
            ShiftModel a = sd.getShiftById(id);
            var companies = _companyDAL.getAllCompany();
            ViewBag.companies = new SelectList(companies, "Id", "Name", a.Company);

            return View(a);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ShiftModel a, HttpPostedFileBase file)
        {
            try
            {
                string directoryPath = Server.MapPath($"~/Images/SubImages/");

                string ExistingFileName = $"{a.Id}_*";

                if (file != null && file.ContentLength > 0)
                {
                    var AlreadyExist = Directory.GetFiles(directoryPath, ExistingFileName);
                    if (AlreadyExist.Length > 0)
                    {
                        System.IO.File.Delete(AlreadyExist[0]);
                    }

                    string fileName = $"{a.Id}_{Path.GetFileName(file.FileName)}";
                    string filePath = Path.Combine(directoryPath, fileName);
                    //string existingFile = Directory.GetFiles(directoryPath, $"{a.Id}_*").FirstOrDefault();
                    //if (existingFile != null)
                    //{
                    //    System.IO.File.Delete(existingFile); // Delete the old file
                    //}

                    file.SaveAs(filePath);
                    a.imagepath = $"~/Images/SubImages/{fileName}";//database me bheja
                }
                sd.UpdateShift(a);
                return RedirectToAction("Index");
            }
            catch 
            {
                return View(a);
            }
        }





        public ActionResult Delete(int id)
        {
            ShiftModel a = sd.getShiftById(id);

            return View(a);


        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Delete(ShiftModel m)
        {
            try
            {
                sd.DeleteShift(m.Id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


    }
}

Views/Shift/Create.cshtml
@model WebApplication4.Models.ShiftModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Shift", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>ShiftModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.start_time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.start_time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.start_time, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.end_time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.end_time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.end_time, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Company, ViewBag.Companies as SelectList, "Select a Company", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.imagepath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file" required />
            @Html.ValidationMessageFor(model => model.imagepath, "", new { @class = "text-danger" })
        </div>
    </div>*@

<div class="form-group">
    @Html.LabelFor(model => model.ImageFile, "Upload Image", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        <input type="file" name="file" class="form-control" accept="image/*" />
        <small class="form-text text-muted"></small>
        @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
    </div>
</div>





    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<!-- Back to List -->
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Shift/Delete.cshtml
@model WebApplication4.Models.ShiftModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShiftModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.start_time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.start_time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.end_time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.end_time)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.companyName)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.companyName)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Shift/Edit.cshtml
@model WebApplication4.Models.ShiftModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@*@using (Html.BeginForm())*@
@using (Html.BeginForm("Edit", "Shift", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ShiftModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.start_time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.start_time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.start_time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.end_time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.end_time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.end_time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Company, (SelectList)ViewBag.companies, "Select Company", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagepath, "Current Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (!string.IsNullOrEmpty(Model.imagepath))
                {
                    <img src="@Url.Content(Model.imagepath)" style="width: 100px; height: auto;" />
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, "Upload New Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" class="form-control" accept="image/*" />
                <small class="form-text text-muted">Upload a new image if you want to change it.</small>
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Shift/Index.cshtml
@model IEnumerable<WebApplication4.Models.ShiftModel>
<html>
<head>
    <meta name="viewport" content="width-device-width" />


    @{
        ViewBag.Title = "Shift List";
    }

</head>


<h2>Shift List</h2>
@*<center>
    @using (Html.BeginForm("Index", "Shift", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="file" name="file" id="file" />
    <input type="submit" value="Upload" />
    }
</center>*@

<p>
    @Html.ActionLink("Create New Shift", "Create")
</p>

<table class="table">
    <thead>
        <tr>
            <th>Shift Name</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Company</th>
            <th>Image</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var shift in Model)
        {
            <tr>
                <td>@shift.Name</td>
                <td>@shift.start_time</td>
                <td>@shift.end_time</td>
                <td>@shift.companyName</td>
                <td>
                    @if (!string.IsNullOrEmpty(shift.imagepath))
                    {
                        <img src="@Url.Content(shift.imagepath)" alt="Shift Image" style="width: 100px; height: auto;" />
                    }
                    else
                    {
                        <span>No Image</span>
                    }
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = shift.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = shift.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

</html>